apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-intro-server
spec:
  selector:
    matchLabels:
      app: k8s-intro-server
  replicas: 4
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 300
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: k8s-intro-server
    spec:
      containers:
      - name: k8s-intro-server
        image: drmikehopper/k8s-intro-server:1.2.0
        ports:
        - containerPort: 4000
        env:
        - name: NODE_ENV
          value: development
        - name: DEBUG
          value: express:server
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
