apiVersion: v1
kind: Service
metadata:
  name: k8s-intro-server-svc
  labels:
    app: k8s-intro-server
spec:
  type: ClusterIP
  selector:
    app: k8s-intro-server
  ports:
  - appProtocol: HTTP
    protocol: TCP
    port: 4000
    targetPort: 4000
