#!/bin/bash

# kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v0.40.2/deploy/static/provider/cloud/deploy.yaml
# kubectl delete -A ValidatingWebhookConfiguration ingress-nginx-admission

kubectl apply -f nginx.yaml

sleep 1
kubectl get all

sleep 1
kubectl get ingress

